// Code generated by "stringer -type=Format -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormatUnknown-0]
	_ = x[FormatFLAC-1]
	_ = x[FormatMP3-2]
	_ = x[FormatM4A-3]
	_ = x[FormatM4B-4]
	_ = x[FormatOgg-5]
	_ = x[FormatOpus-6]
	_ = x[FormatWAV-7]
	_ = x[FormatAIFF-8]
}

const _Format_name = "UnknownFLACMP3M4AM4BOgg VorbisOpusWAVAIFF"

var _Format_index = [...]uint8{0, 7, 11, 14, 17, 20, 30, 34, 37, 41}

func (i Format) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Format_index)-1 {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[idx]:_Format_index[idx+1]]
}
