// Code generated by "stringer -type=ArtworkType -linecomment"; DO NOT EDIT.

package audiometa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArtworkOther-0]
	_ = x[ArtworkIcon-1]
	_ = x[ArtworkOtherIcon-2]
	_ = x[ArtworkFrontCover-3]
	_ = x[ArtworkBackCover-4]
	_ = x[ArtworkLeaflet-5]
	_ = x[ArtworkMedia-6]
	_ = x[ArtworkLeadArtist-7]
	_ = x[ArtworkArtist-8]
	_ = x[ArtworkConductor-9]
	_ = x[ArtworkBand-10]
	_ = x[ArtworkComposer-11]
	_ = x[ArtworkLyricist-12]
	_ = x[ArtworkRecordingLocation-13]
	_ = x[ArtworkDuringRecording-14]
	_ = x[ArtworkDuringPerformance-15]
	_ = x[ArtworkVideoCapture-16]
	_ = x[ArtworkBrightFish-17]
	_ = x[ArtworkIllustration-18]
	_ = x[ArtworkBandLogotype-19]
	_ = x[ArtworkPublisherLogotype-20]
}

const _ArtworkType_name = "OtherFile icon (32x32 PNG)Other file iconFront coverBack coverLeaflet pageMedia (CD/vinyl label)Lead artist/performer/soloistArtist/performerConductorBand/orchestraComposerLyricist/text writerRecording locationDuring recordingDuring performanceMovie/video screen captureA bright colored fishIllustrationBand/artist logotypePublisher/studio logotype"

var _ArtworkType_index = [...]uint16{0, 5, 26, 41, 52, 62, 74, 96, 125, 141, 150, 164, 172, 192, 210, 226, 244, 270, 291, 303, 323, 348}

func (i ArtworkType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ArtworkType_index)-1 {
		return "ArtworkType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArtworkType_name[_ArtworkType_index[idx]:_ArtworkType_index[idx+1]]
}
